const actionTypes = {
  USER_GET_REQUEST: "USER_GET_REQUEST",
  USER_GET_SUCCESS: "USER_GET_SUCCESS",
  USER_GET_FAILURE: "USER_GET_FAILURE",

  CHEF_GET_REQUEST: "CHEF_GET_REQUEST",
  CHEF_GET_SUCCESS: "CHEF_GET_SUCCESS",
  CHEF_GET_FAILURE: "CHEF_GET_FAILURE",

  OUTLET_GET_REQUEST: "OUTLET_GET_REQUEST",
  OUTLET_GET_SUCCESS: "OUTLET_GET_SUCCESS",
  OUTLET_GET_FAILURE: "OUTLET_GET_FAILURE",

  OUTLETS_GET_REQUEST: "OUTLETS_GET_REQUEST",
  OUTLETS_GET_SUCCESS: "OUTLETS_GET_SUCCESS",
  OUTLETS_GET_FAILURE: "OUTLETS_GET_FAILURE",

  CART_GET_REQUEST: "CART_GET_REQUEST",
  CART_GET_SUCCESS: "CART_GET_SUCCESS",
  CART_GET_FAILURE: "CART_GET_FAILURE",

  LOGIN_DRAWER_REQUEST: "LOGIN_DRAWER_REQUEST",

  USER_LOGOUT: "USER_LOGOUT",

  RESET: "RESET",
};

export default actionTypes;
